// src/app/shared/components/modal/modal-form.component.ts
import { Component, Inject, viewChild } from '@angular/core';
import { MAT_DIALOG_DATA, MatDialogRef } from '@angular/material/dialog';
import { MainButtonComponent } from '@components/buttons/main-button.component';
import { MainFormComponent } from '@components/form/main-form.component';
import { LoaderComponent } from '@components/loading/loader.component';
import { LucideSave, LucideX } from '@lucide/angular';
import { Input } from '@shared/types/form';

export interface ModalFormData {
  title?: string;
  inputs: Input[];
  onSubmit: (data: Record<string, unknown>) => void;
  isLoading?: boolean;
  defaultValues?: Record<string, unknown>;
  columns?: number;
  isPending?: boolean;
  saveLabel?: string;
  cancelLabel?: string;
}

@Component({
  selector: 'app-modal-form',
  standalone: true,
  imports: [MainButtonComponent, MainFormComponent, LoaderComponent, LucideSave, LucideX],
  template: `
    <div class="ale-form-modal">
      <div class="ale-form-modal-header">
        <div class="ale-form-modal-title">{{ data.title ?? 'Formulario' }}</div>
        <button class="ale-form-modal-close" (click)="close()" aria-label="Cerrar">
          <svg lucideX size="18"></svg>
        </button>
      </div>

      <div class="ale-form-modal-body">
        <app-loader [isPending]="data.isPending ?? false"></app-loader>
        <app-main-form
          #form
          [inputs]="data.inputs"
          [isLoading]="data.isLoading ?? false"
          [defaultValues]="data.defaultValues ?? {}"
          [columns]="data.columns"
          (onSubmit)="submit($event)"
        ></app-main-form>
      </div>

      <div class="ale-form-modal-footer">
        <app-main-button variant="outlined" (click)="close()" [disabled]="data.isPending ?? false">
          <svg lucideX size="16"></svg>
          {{ data.cancelLabel ?? 'Cancelar' }}
        </app-main-button>
        <app-main-button (click)="save()" [loading]="data.isPending ?? false">
          <svg lucideSave size="16"></svg>
          {{ data.saveLabel ?? 'Guardar' }}
        </app-main-button>
      </div>
    </div>
  `,
  styles: [`
    .ale-form-modal { position: relative; }
    .ale-form-modal-header {
      display: flex; align-items: center; justify-content: space-between;
      padding: 22px 22px 8px;
    }
    .ale-form-modal-title { font-weight: 700; color: var(--color-text); letter-spacing: -0.02em; font-size: 1.3rem; }
    .ale-form-modal-close {
      width: 36px; height: 36px; border-radius: 50%; border: 1px solid var(--color-border);
      background: var(--color-bgCard); color: var(--color-text); cursor: pointer;
      display: flex; align-items: center; justify-content: center; transition: all 0.2s ease;
    }
    .ale-form-modal-close:hover { color: var(--color-error); border-color: var(--color-error); background: var(--color-errorBg); transform: rotate(90deg); }
    .ale-form-modal-body { padding: 18px 22px; overflow-y: auto; max-height: 70vh; }
    .ale-form-modal-footer { display: flex; justify-content: flex-end; gap: 12px; padding: 14px 22px 22px; }
  `],
})
export class ModalFormComponent {
  readonly formRef = viewChild<MainFormComponent>('form');

  constructor(
    @Inject(MAT_DIALOG_DATA) readonly data: ModalFormData,
    private dialogRef: MatDialogRef<ModalFormComponent>,
  ) {}

  submit(data: Record<string, unknown>): void {
    this.data.onSubmit(data);
  }

  save(): void {
    this.formRef()?.save();
  }

  getValue(name: string): unknown {
    return this.formRef()?.getValue(name);
  }

  getValues(): Record<string, unknown> {
    return this.formRef()?.getValues() ?? {};
  }

  close(): void {
    this.dialogRef?.close();
  }
}

// src/ui/modal/ModalForm.tsx
import React, { useRef } from 'react';
import { Modal } from '@/ui/modal/Modal';
import { MainForm } from '@/ui/form/MainForm';
import { MainButton } from '@/ui/buttons/MainButton';
import { Save, X } from 'lucide-react';
import { Box } from '@mui/material';
import type { Input } from '@/ui/ts/form';
import type { SxProps, Theme } from '@mui/material';
import Loader from '../loading/Loader';

export type RefForm = {
    save: () => void;
    getValues: () => any;
    getValue: (fieldName?: string) => any;
    setValue: any;
    reset: any;
    watch: any;
    trigger: any;
};

interface ModalFormProps {
    open: boolean;
    onClose: () => void;
    title?: string;
    inputs: Input[];
    onSubmit: (data: any) => void;
    maxWidth?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | false;
    fullWidth?: boolean;
    isLoading?: boolean;
    defaultValues?: any;
    sx?: SxProps<Theme>;
    saveLabel?: string;
    cancelLabel?: string;
    columns?: number;
    isPending?: boolean;
}

export const ModalForm: React.FC<ModalFormProps> = ({
    open,
    onClose,
    title,
    inputs,
    onSubmit,
    maxWidth = 'sm',
    fullWidth = true,
    isLoading = false,
    defaultValues,
    sx,
    saveLabel = 'Guardar',
    cancelLabel = 'Cancelar',
    columns,
    isPending = false
}) => {
    const formRef = useRef<RefForm | null>(null);

    const handleSave = () => {
        formRef.current?.save();
    };

    return (
        <Modal
            open={open}
            onClose={onClose}
            title={title}
            maxWidth={maxWidth}
            fullWidth={fullWidth}
            sx={sx}
            actions={
                <Box sx={{ display: 'flex', gap: 1.5 }}>
                    <MainButton
                        variant="outlined"
                        onClick={onClose}
                        sx={{
                            gap: 1,
                            color: 'var(--color-error)',
                            borderColor: 'var(--color-error)',
                            '&:hover': {
                                borderColor: 'var(--color-error)',
                                backgroundColor: 'var(--color-errorBg)',
                            },
                        }}
                    >
                        <X size={16} /> {cancelLabel}
                    </MainButton>
                    <MainButton
                        variant="contained"
                        onClick={handleSave}
                        loading={isLoading}
                        sx={{
                            gap: 1,
                            background: 'linear-gradient(135deg, var(--color-primary), var(--color-secondary))',
                            color: 'var(--color-textOnPrimary) !important',
                            '&:hover': {
                                background: 'linear-gradient(135deg, var(--color-primary), var(--color-secondary))',
                            },
                        }}
                    >
                        <Save size={16} /> {saveLabel}
                    </MainButton>
                </Box>
            }
        >
            <Box sx={{ pt: 1 }}>
                <Loader isPending={isPending} />
                <MainForm
                    ref={formRef}
                    inputs={inputs}
                    onSubmit={onSubmit}
                    isLoading={isLoading}
                    defaultValues={defaultValues}
                    columns={columns}
                />
            </Box>
        </Modal>
    );
};

export default ModalForm;
