// src/pages/public/auth/Login.tsx
import { MainForm } from "@/components/form/MainForm";
import { inputs } from "./inputs";
import { Typography, Button, Stack } from "@mui/material";
import { useLogin } from "./useLogin";
import AuthLayout from "./AuthLayout";
import { MfaModal } from "./MfaModal";

const Login = () => {
    const { formRef, handleSubmit, isPending, toForgot, openMfa, pendingLogin, handleCloseMfa } = useLogin();

    return (
        <>
            <AuthLayout subtitle="Ingresa tus credenciales para acceder">
                <Stack gap={0.5} mb={4}>
                    <Typography
                        variant="h5"
                        sx={{ fontWeight: 800, color: 'var(--color-text)', letterSpacing: -0.3 }}
                    >
                        Iniciar sesión
                    </Typography>
                    <Typography
                        variant="body2"
                        sx={{ color: 'var(--color-text)', opacity: 0.55 }}
                    >
                        Accede con tu usuario y contraseña
                    </Typography>
                </Stack>

                <MainForm
                    ref={formRef as any}
                    inputs={inputs}
                    onSubmit={handleSubmit}
                    columns={1}
                    sx={{ width: '100%' }}
                    sxForm={{ gap: 2 }}
                />

                <Button
                    fullWidth
                    variant="contained"
                    onClick={() => formRef.current?.save()}
                    loading={isPending}
                    sx={{
                        mt: 3,
                        py: 1.6,
                        borderRadius: '12px',
                        textTransform: 'none',
                        fontSize: '1rem',
                        fontWeight: 700,
                        letterSpacing: 0.2,
                        background: 'linear-gradient(90deg, #2563eb, #1a3ea8)',
                        boxShadow: '0 8px 24px -6px rgba(37,99,235,0.45)',
                        '&:hover': {
                            background: 'linear-gradient(90deg, #1d55d4, #163399)',
                            boxShadow: '0 12px 28px -8px rgba(37,99,235,0.55)',
                            transform: 'translateY(-1px)',
                        },
                    }}
                >
                    Acceder
                </Button>

                <Typography
                    onClick={toForgot}
                    variant="body2"
                    sx={{
                        mt: 2.5,
                        textAlign: 'center',
                        color: 'var(--color-primary)',
                        cursor: 'pointer',
                        fontWeight: 500,
                        '&:hover': { opacity: 0.75 },
                    }}
                >
                    ¿Olvidaste tu contraseña?
                </Typography>
            </AuthLayout>

            <MfaModal
                open={openMfa}
                onClose={handleCloseMfa}
                pendingLogin={pendingLogin}
            />
        </>
    );
};

export default Login;

// src/app/pages/public/auth/login.component.ts
import { Component, signal } from '@angular/core';
import { Router } from '@angular/router';
import { AuthLayoutComponent } from '@pages/public/auth/auth-layout.component';
import { MainFormComponent } from '@components/form/main-form.component';
import { MainButtonComponent } from '@components/buttons/main-button.component';
import { MfaModalComponent } from '@pages/public/auth/mfa-modal.component';
import { RequestService } from '@services/request.service';
import { ModalService } from '@components/modal/modal.service';
import { AuthStore } from '@core/auth/auth.store';
import { ERRORS, ResponseLogin } from '@features/auth';
import { Input, f } from '@shared/types/form';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [AuthLayoutComponent, MainFormComponent, MainButtonComponent],
  template: `
    <app-auth-layout subtitle="Ingresa tus credenciales para acceder">
      <div class="login-heading">
        <div class="login-title">Iniciar sesión</div>
        <div class="login-subtitle">Accede con tu usuario y contraseña</div>
      </div>

      <app-main-form
        #form
        [inputs]="inputs"
        (onSubmit)="handleSubmit($event)"
        [columns]="1"
      ></app-main-form>

      <app-main-button variant="contained" [gradient]="true" [loading]="isPending()" (click)="form.save()" [fullWidth]="true" class="login-button">
        Acceder
      </app-main-button>

      <div class="login-forgot" (click)="toForgot()">¿Olvidaste tu contraseña?</div>
    </app-auth-layout>
  `,
  styles: [`
    .login-heading { margin-bottom: 4rem; display: flex; flex-direction: column; gap: 0.5rem; }
    .login-title { font-weight: 800; color: var(--color-text); letter-spacing: -0.3px; font-size: 1.5rem; }
    .login-subtitle { color: var(--color-text); opacity: 0.55; font-size: 0.875rem; }
    .login-button { margin-top: 3rem; }
    .login-forgot {
      margin-top: 2.5rem;
      text-align: center;
      color: var(--color-primary);
      cursor: pointer;
      font-weight: 500;
      font-size: 0.875rem;
    }
    .login-forgot:hover { opacity: 0.75; }
  `],
})
export class LoginComponent {
  readonly inputs: Input[] = [
    f.text('username').label('Usuario').value('').required().build(),
    f.password('password').label('Contraseña').value('').required().build(),
  ];

  readonly openMfa = signal(false);
  readonly pendingLogin = signal<ResponseLogin | null>(null);
  readonly isPending = signal(false);

  constructor(
    private readonly request: RequestService,
    private readonly modal: ModalService,
    private readonly auth: AuthStore,
    private readonly router: Router,
  ) {}

  handleSubmit(data: Record<string, unknown>): void {
    const request = this.request.create<ResponseLogin>({ url: 'auth/login', method: 'POST' });
    this.isPending.set(true);
    void request.execute(data).then((res) => {
      if (!res.mfaOk) {
        const dialog = this.modal.open<MfaModalComponent>(MfaModalComponent, {
          data: res,
          maxWidth: '520px',
        });
        dialog.afterClosed().subscribe(() => {
          this.pendingLogin.set(null);
          this.openMfa.set(false);
        });
        this.pendingLogin.set(res);
        this.openMfa.set(true);
        return;
      }
      this.auth.loginUser(res);
      this.pendingLogin.set(null);
      this.openMfa.set(false);
      void this.router.navigate(['/']);
    }).catch((error: unknown) => {
      const code = (error as { code?: number } | null)?.code;
      if (Number(code) === ERRORS.MFA_PENDING) return;
      throw error;
    }).finally(() => this.isPending.set(false));
  }

  toForgot(): void {
    void this.router.navigate(['/auth/forgot']);
  }
}
