// src/app/pages/gestion-usuarios/roles/details-roles.component.ts
import { Component } from '@angular/core';
import { DetailsComponent } from '@components/crud/details.component';
import { Input, f } from '@shared/types/form';

@Component({
  selector: 'app-details-roles',
  standalone: true,
  imports: [DetailsComponent],
  template: `
    <app-details
      [inputs]="inputs"
      title="Rol"
      urlCreate="/roles/create"
      urlUpdate="/roles/update"
      keyCache="roles"
      ReadEndpoint="/roles/Read"
      [permission]="permissionModule"
    ></app-details>
  `,
  styles: [`:host { display: block; }`],
})
export class DetailsRolesComponent {
  readonly permissionModule = 'GESTION_ROLES';

  readonly inputs: Input[] = [
    f.text('name').label('Nombre').required().maxLength(75).build(),
    f.area('description').label('Descripción').required().maxLength(250).build(),
  ];
}

// src/pages/private/access/roles/details/DetailsRoles.tsx
import { ROLES } from "@/common";
import { Details } from "@/components/crud/details/Details";
import { inputsRoles } from "./inputs";

const DetailsRoles = () => {
    return (
        <Details
            inputs={inputsRoles}
            keyCache="roles"
            ReadEndpoint="/roles/Read"
            title="Rol"
            urlCreate="/roles/create"
            urlUpdate="/roles/update"
            permission={ROLES.MODULE}
        />
    );
};

export default DetailsRoles;
