// src/app/pages/public/auth/reset-password.component.ts
import { Component, signal } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { AuthLayoutComponent } from '@pages/public/auth/auth-layout.component';
import { MainFormComponent } from '@components/form/main-form.component';
import { MainButtonComponent } from '@components/buttons/main-button.component';
import { RequestService } from '@services/request.service';
import { Input, f } from '@shared/types/form';

@Component({
  selector: 'app-reset-password',
  standalone: true,
  imports: [AuthLayoutComponent, MainFormComponent, MainButtonComponent],
  template: `
    <app-auth-layout subtitle="Crea una nueva contraseña segura para tu cuenta">
      <div class="auth-heading">
        <div class="auth-title">Restablecer contraseña</div>
        <div class="auth-subtitle">Ingresa tu nueva contraseña</div>
      </div>

      <app-main-form
        #form
        [inputs]="inputs"
        (onSubmit)="handleSubmit($event)"
        [columns]="1"
      ></app-main-form>

      <app-main-button variant="contained" [gradient]="true" [loading]="isPending()" (click)="form.save()" [fullWidth]="true" class="auth-button">
        Restablecer contraseña
      </app-main-button>

      <div class="auth-link" (click)="toLogin()">Volver al inicio de sesión</div>
    </app-auth-layout>
  `,
  styles: [`
    .auth-heading { margin-bottom: 4rem; display: flex; flex-direction: column; gap: 0.5rem; }
    .auth-title { font-weight: 800; color: var(--color-text); letter-spacing: -0.3px; font-size: 1.5rem; }
    .auth-subtitle { color: var(--color-text); opacity: 0.55; font-size: 0.875rem; }
    .auth-button { margin-top: 3rem; }
    .auth-link {
      margin-top: 2.5rem;
      text-align: center;
      color: var(--color-primary);
      cursor: pointer;
      font-weight: 500;
      font-size: 0.875rem;
    }
    .auth-link:hover { opacity: 0.75; }
  `],
})
export class ResetPasswordComponent {
  readonly inputs: Input[] = [
    f.password('newPassword').label('Nueva contraseña').required().minLength(6).build(),
  ];

  readonly isPending = signal(false);

  constructor(
    private request: RequestService,
    private router: Router,
    private route: ActivatedRoute,
  ) {}

  toLogin(): void {
    void this.router.navigate(['/auth/login']);
  }

  handleSubmit(data: Record<string, unknown>): void {
    const token = this.route.snapshot.paramMap.get('token') ?? '';
    const request = this.request.create({ url: 'auth/reset-password', method: 'PATCH' });
    this.isPending.set(true);
    void request.execute({ ...data, token }).finally(() => {
      this.isPending.set(false);
      this.toLogin();
    });
  }
}

// src/pages/private/auth/ForgotPassword/reset.password/ResetPassword.tsx
import { MainForm } from "@/ui/form/MainForm";
import { useResetPassword } from "./useResetPassword";
import { inputs } from "./inputs";
import { Typography, Button, Stack } from "@mui/material";
import AuthLayout from "@/pages/public/auth/AuthLayout";

const ResetPassword = () => {
    const { formRef, handleSubmbit, toLogin } = useResetPassword();

    return (
        <AuthLayout subtitle="Crea una nueva contraseña segura para tu cuenta">
            <Stack gap={0.5} mb={4}>
                <Typography
                    variant="h5"
                    sx={{ fontWeight: 800, color: 'var(--color-text)', letterSpacing: -0.3 }}
                >
                    Restablecer contraseña
                </Typography>
                <Typography
                    variant="body2"
                    sx={{ color: 'var(--color-text)', opacity: 0.55 }}
                >
                    Ingresa tu nueva contraseña
                </Typography>
            </Stack>

            <MainForm
                ref={formRef as any}
                inputs={inputs}
                onSubmit={handleSubmbit}
                columns={1}
                sx={{ width: '100%' }}
                sxForm={{ gap: 2 }}
            />

            <Button
                fullWidth
                variant="contained"
                onClick={() => formRef.current?.save()}
                sx={{
                    mt: 3,
                    py: 1.6,
                    borderRadius: '12px',
                    textTransform: 'none',
                    fontSize: '1rem',
                    fontWeight: 700,
                    letterSpacing: 0.2,
                    background: 'linear-gradient(90deg, #2563eb, #1a3ea8)',
                    boxShadow: '0 8px 24px -6px rgba(37,99,235,0.45)',
                    '&:hover': {
                        background: 'linear-gradient(90deg, #1d55d4, #163399)',
                        boxShadow: '0 12px 28px -8px rgba(37,99,235,0.55)',
                        transform: 'translateY(-1px)',
                    },
                }}
            >
                Cambiar contraseña
            </Button>

            <Typography
                onClick={toLogin}
                variant="body2"
                sx={{
                    mt: 2.5,
                    textAlign: 'center',
                    color: 'var(--color-primary)',
                    cursor: 'pointer',
                    fontWeight: 500,
                    '&:hover': { opacity: 0.75 },
                }}
            >
                Volver al inicio de sesión
            </Typography>
        </AuthLayout>
    );
};

export default ResetPassword;
