// src/common/components/crud/list/List.tsx
import { MainTable, Title, MainCard, MainButton, MainFilter, useAuth, TYPES_AUTHORIZATIONS } from "@/common";
import { useList, type PropsHook } from "./useList";
import type { ColumnDef } from "@tanstack/react-table";
import { Save } from "lucide-react";
import { useNavigate } from "react-router";
import type { Input } from "@/components/ts/form";
import { useMemo } from "react";
import ButtonStatus from "../../filter/ButtonStatus";


interface Props<T> extends PropsHook {
  title: string;
  name: string;
  toCreate?: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  columns: ColumnDef<T, any>[];
  queryKey: string;
  endpoint: string;
  enabled?: boolean;
  onClickCreate?: () => void;
  filters?: Input[];
  initialFilter?: Record<string, unknown>;
  isPending?: boolean;
  permission?: string;
  enabledCreate?: boolean;
  useMainFilter?: boolean;
  disabledButtonStatus?: boolean;
}

export const List = <T,>({
  title,
  name,
  queryKey,
  endpoint,
  enabled = false,
  columns,
  toCreate,
  onClickCreate,
  filters,
  initialFilter,
  isPending = false,
  permission,
  enabledCreate,
  useMainFilter = false,
  disabledButtonStatus = false,
  minDataFetch
}: Props<T>) => {
  const { validarPermiso } = useAuth();

  const canCreate = enabledCreate ?? (permission ? validarPermiso(permission, TYPES_AUTHORIZATIONS.Write) : undefined);

  const {
    data,
    isLoading,
    isFetched,
    get,
    columnFilters,
    onColumnFilterChange,
    onColumnFilterBlur,
    page,
    pageSize,
    hasNextPage,
    setPage,
    setPageSize,
    totalPages,
    totalRecords
  } = useList<T>({
    endpoint,
    enabled,
    queryKey,
    minDataFetch,
  });
  const nav = useNavigate();

  const fnCreate = () => onClickCreate ? onClickCreate() : nav(toCreate ?? '/')

  const objFilters = useMemo(() => {
    if (!filters) return {};

    return ({
      initialValues: initialFilter,
      inputs: filters,
    });
  }, [filters, initialFilter]);


  return (
    <>
      <MainCard>
        {(useMainFilter) && (
          <MainFilter
            title={title}
            get={get}
            isPending={isLoading || isPending}
            {...objFilters}
          />
        )}
        <Title title={title}>

          {!disabledButtonStatus && (
            <ButtonStatus get={get} isPending={isLoading || isPending} />
          )}

          {canCreate && (
            <MainButton variant="contained" sx={{ display: 'flex', alignItems: 'center', gap: 1.5 }} onClick={fnCreate}>
              Crear <Save size={18} />
            </MainButton>
          )}

        </Title>

      </MainCard>
      <MainCard sx={{ p: 2, minHeight: '60%', borderRadius: '10px', paddingBlock: '1rem' }}>
        <MainTable<T>
          name={name}
          columns={columns}
          data={data}
          isLoading={isLoading || isPending}
          isFetched={isFetched}
          columnFilters={columnFilters}
          onColumnFilterChange={onColumnFilterChange}
          onColumnFilterBlur={onColumnFilterBlur}
          page={page}
          pageSize={pageSize}
          hasNextPage={hasNextPage}
          onPageChange={setPage}
          onPageSizeChange={setPageSize}
          totalPages={totalPages}
          totalRecords={totalRecords}
        />
    
      </MainCard></>
  );
};

// src/app/shared/components/crud/list.component.ts
import { Component, input, OnInit, OnDestroy, signal, computed } from '@angular/core';
import { MainCardComponent } from '@components/cards/main-card.component';
import { MainTitleBarComponent } from '@components/crud/main-title-bar.component';
import { MainTableComponent } from '@components/tables/main-table.component';
import { ListQuery, ListQueryFactory } from '@services/list-query.service';
import { ListRegistry } from '@services/list-registry.service';
import { ColumnConfig } from '@shared/types/table';

export interface ListProps {
  endpoint: string;
  title: string;
  queryKey: string;
  columns: ColumnConfig<Record<string, unknown>>[];
  toCreate?: string;
  name?: string;
  permission?: string;
  minDataFetch?: number;
  initialFilter?: Record<string, unknown>;
  disabledButtonStatus?: boolean;
}

@Component({
  selector: 'app-list',
  standalone: true,
  imports: [
    MainCardComponent,
    MainTitleBarComponent,
    MainTableComponent,
  ],
  template: `
    <div style="display: flex; flex-direction: column; gap: 24px;">
      <app-main-card>
        <app-main-title-bar
          [title]="title()"
          [toCreate]="toCreate()"
          [name]="name()"
          [permission]="permission()"
          [get]="getFn"
          [isPending]="list()?.isLoading() ?? false"
          [disabledButtonStatus]="disabledButtonStatus()"
          [statusActive]="statusActive()"
          [toggleStatus]="toggleStatusFn"
        ></app-main-title-bar>
      </app-main-card>

      <app-main-card [padding]="'1rem'">
        <app-main-table
          [data]="list()?.data() ?? []"
          [columns]="columns()"
          [isLoading]="list()?.isLoading() ?? false"
          [isFetched]="list()?.isFetched() ?? false"
          [columnFilters]="list()?.columnFilters() ?? {}"
          [onColumnFilterChange]="onColumnFilterChange"
          [onColumnFilterBlur]="onColumnFilterBlur"
          [page]="list()?.page() ?? 1"
          [pageSize]="list()?.pageSize() ?? 10"
          [totalPages]="list()?.totalPages() ?? 0"
          [totalRecords]="list()?.totalRecords() ?? 0"
          [onPageChange]="onPageChange"
          [onPageSizeChange]="onPageSizeChange"
          [name]="name()"
        ></app-main-table>
      </app-main-card>
    </div>
  `,
  styles: [`
    :host { display: block; }
  `],
})
export class ListComponent implements OnInit, OnDestroy {
  endpoint = input('');
  title = input('');
  queryKey = input('');
  columns = input<ColumnConfig<Record<string, unknown>>[]>([]);
  toCreate = input<string | undefined>(undefined);
  name = input<string | undefined>(undefined);
  permission = input<string | undefined>(undefined);
  minDataFetch = input<number | undefined>(undefined);
  initialFilter = input<Record<string, unknown> | undefined>(undefined);
  disabledButtonStatus = input(false);

  readonly list = signal<ListQuery<Record<string, unknown>> | null>(null);

  readonly statusActive = computed(
    () => String(this.list()?.filters()['active'] ?? true) !== 'false',
  );

  constructor(
    private listFactory: ListQueryFactory,
    private registry: ListRegistry,
  ) {}

  ngOnInit(): void {
    const list = this.listFactory.create<Record<string, unknown>>({
      url: this.endpoint(),
      key: this.queryKey(),
      minDataFetch: this.minDataFetch(),
    });

    const initial = this.initialFilter();
    if (initial) {
      Object.entries(initial).forEach(([key, value]) => {
        list.addFilter(key, value);
      });
    }

    list.init();
    this.list.set(list);
    this.registry.register(this.queryKey(), list);
  }

  ngOnDestroy(): void {
    this.registry.unregister(this.queryKey());
  }

  readonly getFn = () => {
    this.list()?.refetch();
  };

  readonly onColumnFilterChange = (name: string, value: string) => {
    this.list()?.onColumnFilterChange(name, value);
  };

  readonly onColumnFilterBlur = (name: string, value: string) => {
    this.list()?.onColumnFilterBlur(name, value);
  };

  readonly onPageChange = (page: number) => {
    this.list()?.setPage(page);
  };

  readonly onPageSizeChange = (pageSize: number) => {
    this.list()?.setPageSize(pageSize);
  };

  readonly toggleStatusFn = () => {
    const next = !this.statusActive();
    this.list()?.setFilters({ active: next });
  };
}
