// src/app/shared/components/layout/theme-toggle.component.ts
import { Component } from '@angular/core';
import { ThemeService } from '@core/theme/theme.service';
import { LucideSun, LucideMoon } from '@lucide/angular';

@Component({
  selector: 'app-theme-toggle',
  standalone: true,
  imports: [LucideSun, LucideMoon],
  template: `
    <button
      class="toolbar-toggle"
      (click)="toggleTheme()"
      [attr.title]="theme.isDark() ? 'Cambiar a modo claro' : 'Cambiar a modo oscuro'"
    >
      @if (theme.isDark()) {
        <svg lucideSun size="20"></svg>
      } @else {
        <svg lucideMoon size="20"></svg>
      }
    </button>
  `,
  styles: [`
    .toolbar-toggle {
      display: flex;
      align-items: center;
      justify-content: center;
      width: 44px;
      height: 44px;
      border-radius: 12px;
      border: 1px solid var(--color-border);
      background-color: var(--color-sidebar);
      backdrop-filter: blur(20px);
      color: var(--color-text);
      cursor: pointer;
      transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
      position: relative;
      overflow: hidden;
    }
    .toolbar-toggle:hover {
      background-color: var(--color-hover);
      border-color: var(--color-primary);
      transform: translateY(-2px);
      box-shadow: var(--color-toggleHoverShadow);
    }
    .toolbar-toggle:active {
      transform: translateY(0px);
    }
    .toolbar-toggle svg {
      transition: transform 0.3s cubic-bezier(0.4, 0, 0.2, 1);
      filter: var(--color-toggleIconShadow);
    }
  `],
})
export class ThemeToggleComponent {
  constructor(public theme: ThemeService) {}

  toggleTheme(): void {
    this.theme.toggleTheme();
  }
}

// src/ui/layout/ThemeToggle.tsx
import React from 'react';
import { useTheme } from '@/hooks/useTheme';
import { Sun, Moon } from 'lucide-react';
import { Box } from '@mui/material';

export const ThemeToggle: React.FC = () => {
    const { isDark, toggleTheme } = useTheme();

    return (
        <Box
            component="button"
            onClick={toggleTheme}
            sx={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                width: 44,
                height: 44,
                borderRadius: '12px',
                border: '1px solid var(--color-border)',
                backgroundColor: 'var(--color-sidebar)',
                backdropFilter: 'blur(20px)',
                color: 'var(--color-text)',
                cursor: 'pointer',
                transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
                position: 'relative',
                overflow: 'hidden',
                '&::before': {
                    content: '""',
                    position: 'absolute',
                    inset: 0,
                    borderRadius: '12px',
                    padding: '1px',
                    background: 'var(--color-toggleBorderGlow)',
                    WebkitMask: 'linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0)',
                    WebkitMaskComposite: 'xor',
                    maskComposite: 'exclude',
                    opacity: 0,
                    transition: 'opacity 0.3s ease',
                },
                '&:hover': {
                    backgroundColor: 'var(--color-hover)',
                    borderColor: 'var(--color-primary)',
                    transform: 'translateY(-2px)',
                    boxShadow: 'var(--color-toggleHoverShadow)',
                    '&::before': {
                        opacity: 1,
                    },
                    '& svg': {
                        transform: 'rotate(15deg) scale(1.1)',
                    },
                },
                '&:active': {
                    transform: 'translateY(0px)',
                },
                '& svg': {
                    transition: 'transform 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
                    filter: 'var(--color-toggleIconShadow)',
                },
            }}
            title={isDark ? 'Cambiar a modo claro' : 'Cambiar a modo oscuro'}
        >
            {isDark ? <Sun size={20} /> : <Moon size={20} />}
        </Box>
    );
};

export default ThemeToggle;
