// src/ui/view-details/DetailsView.tsx
import { Box, Typography, Divider } from '@mui/material';
import type { DetailField } from '@/common/types/details';

interface Props {
    fields: DetailField[];
    data: Record<string, unknown>;
}

export const DetailsView: React.FC<Props> = ({ fields, data }) => {
    return (
        <Box sx={{
            padding: 2,
        }}>
            {fields.map((field, index) => {
                const raw = data[field.name];
                const rendered = field.value ? field.value(raw) : raw;
                const displayValue = rendered !== null && rendered !== undefined && rendered !== ''
                    ? String(rendered)
                    : '—';
                const Icon = field.icon;

                return (
                    <Box key={field.name}>
                        {index > 0 && (
                            <Divider sx={{ borderColor: 'var(--color-border)', opacity: 0.4, my: 2 }} />
                        )}
                        <Box sx={{
                            display: 'flex',
                            alignItems: 'flex-start',
                            gap: 2.5,
                        }}>
                            {Icon && (
                                <Box sx={{
                                    width: 40,
                                    height: 40,
                                    borderRadius: '12px',
                                    display: 'flex',
                                    alignItems: 'center',
                                    justifyContent: 'center',
                                    flexShrink: 0,
                                    bgcolor: 'var(--color-primarySoft)',
                                    color: 'var(--color-primary)',
                                }}>
                                    <Icon size={18} />
                                </Box>
                            )}
                            <Box sx={{ flex: 1, minWidth: 0, pt: Icon ? 0.5 : 0 }}>
                                <Typography
                                    variant="caption"
                                    sx={{
                                        color: 'var(--color-text-secondary)',
                                        fontWeight: 600,
                                        letterSpacing: '0.05em',
                                        textTransform: 'uppercase',
                                        fontSize: '0.65rem',
                                        display: 'block',
                                        mb: 0.3,
                                    }}
                                >
                                    {field.label}
                                </Typography>
                                <Typography
                                    variant="body1"
                                    sx={{
                                        fontWeight: 600,
                                        color: 'var(--color-text)',
                                        fontSize: '0.9rem',
                                        lineHeight: 1.5,
                                        wordBreak: 'break-word',
                                    }}
                                >
                                    {displayValue}
                                </Typography>
                            </Box>
                        </Box>
                    </Box>
                );
            })}
        </Box>
    );
};

export default DetailsView;

// src/app/shared/components/view-details/details-view.component.ts
import { Component, input } from '@angular/core';
import { DetailField } from '@shared/types/details';
import { IconComponent } from '@components/icon/icon.component';

@Component({
  selector: 'app-details-view',
  standalone: true,
  imports: [IconComponent],
  template: `
    <div class="ale-details">
      @for (field of fields(); track field.name; let index = $index) {
        <div class="ale-detail-row">
          @if (index > 0) {
            <div class="ale-detail-divider"></div>
          }
          <div class="ale-detail-body">
            @if (field.icon) {
              <div class="ale-detail-icon">
                <app-icon [name]="field.icon" [size]="18"></app-icon>
              </div>
            }
            <div class="ale-detail-content">
              <div class="ale-detail-label">{{ field.label }}</div>
              <div class="ale-detail-value" [title]="stringValue(field)">{{ stringValue(field) }}</div>
            </div>
          </div>
        </div>
      }
    </div>
  `,
  styles: [`
    .ale-details { padding: 16px; }
    .ale-detail-row { padding: 8px 0; }
    .ale-detail-divider { border-top: 1px solid var(--color-border); opacity: 0.4; margin: 16px 0; }
    .ale-detail-body { display: flex; align-items: flex-start; gap: 20px; }
    .ale-detail-icon {
      width: 40px; height: 40px; border-radius: 12px; flex-shrink: 0;
      background: var(--color-primarySoft); color: var(--color-primary);
      display: flex; align-items: center; justify-content: center;
    }
    .ale-detail-content { flex: 1; min-width: 0; padding-top: 2px; }
    .ale-detail-label {
      color: var(--color-text); opacity: 0.6; font-weight: 600; letter-spacing: 0.05em;
      text-transform: uppercase; font-size: 0.65rem; display: block; margin-bottom: 4px;
    }
    .ale-detail-value {
      font-weight: 600; color: var(--color-text); font-size: 0.9rem; line-height: 1.5; word-break: break-word;
    }
  `],
})
export class DetailsViewComponent {
  fields = input<DetailField[]>([]);
  data = input<Record<string, unknown>>({});

  stringValue(field: DetailField): string {
    const raw = this.data()[field.name];
    const rendered = field.value ? field.value(raw) : raw;
    const value = rendered !== null && rendered !== undefined && rendered !== '' ? String(rendered) : '—';
    return value;
  }
}
