// src/app/shared/components/modal/confirm-dialog.component.ts
import { Component, Inject } from '@angular/core';
import { MAT_DIALOG_DATA, MatDialogRef } from '@angular/material/dialog';
import { MatButtonModule } from '@angular/material/button';
import { LucideAlertTriangle, LucideXCircle, LucideInfo, LucideCheckCircle } from '@lucide/angular';
import { MainButtonComponent } from '@components/buttons/main-button.component';

export type ConfirmDialogType = 'warning' | 'error' | 'info' | 'success';

export interface ConfirmDialogData {
  title: string;
  message: string;
  type?: ConfirmDialogType;
  confirmText?: string;
  cancelText?: string;
  confirmColor?: 'primary' | 'error' | 'warning' | 'success';
  isLoading?: boolean;
}

@Component({
  selector: 'app-confirm-dialog',
  standalone: true,
  imports: [MatButtonModule, MainButtonComponent, LucideAlertTriangle, LucideXCircle, LucideInfo, LucideCheckCircle],
  template: `
    <div class="ale-confirm">
      <div class="ale-confirm-header">
        <div class="ale-confirm-title">{{ title() }}</div>
        <button class="ale-confirm-close" (click)="close(false)" aria-label="Cerrar">&times;</button>
      </div>

      <div class="ale-confirm-body">
        <div class="ale-confirm-icon" [style.backgroundColor]="iconBg()" [style.color]="iconColor()">
          @switch (type()) {
            @case ('warning') { <svg lucideAlertTriangle size="32"></svg> }
            @case ('error') { <svg lucideXCircle size="32"></svg> }
            @case ('info') { <svg lucideInfo size="32"></svg> }
            @case ('success') { <svg lucideCheckCircle size="32"></svg> }
          }
        </div>
        <div class="ale-confirm-message">{{ message() }}</div>
      </div>

      <div class="ale-confirm-footer">
        <app-main-button variant="outlined" (click)="close(false)" [disabled]="isLoading()">
          {{ cancelText() }}
        </app-main-button>
        <app-main-button (click)="confirm()" [disabled]="isLoading()">
          @if (isLoading()) {
            Procesando...
          } @else {
            {{ confirmText() }}
          }
        </app-main-button>
      </div>
    </div>
  `,
  styles: [`
    .ale-confirm { position: relative; }
    .ale-confirm-header {
      display: flex; align-items: center; justify-content: space-between;
      padding: 22px 22px 4px;
    }
    .ale-confirm-title { font-weight: 700; color: var(--color-text); letter-spacing: -0.02em; font-size: 1.3rem; }
    .ale-confirm-close {
      width: 36px; height: 36px; border-radius: 50%; border: 1px solid var(--color-border);
      background: var(--color-bgCard); color: var(--color-text); cursor: pointer; font-size: 22px; line-height: 1;
    }
    .ale-confirm-close:hover { color: var(--color-error); border-color: var(--color-error); background: var(--color-errorBg); }
    .ale-confirm-body { display: flex; flex-direction: column; align-items: center; gap: 16px; padding: 24px; }
    .ale-confirm-icon { width: 64px; height: 64px; border-radius: 50%; display: flex; align-items: center; justify-content: center; }
    .ale-confirm-message { color: var(--color-text); text-align: center; opacity: 0.9; line-height: 1.6; }
    .ale-confirm-footer { display: flex; gap: 12px; padding: 20px 22px; }
    .ale-confirm-footer app-main-button { flex: 1; display: block; }
  `],
})
export class ConfirmDialogComponent {
  constructor(
    @Inject(MAT_DIALOG_DATA) readonly dialogData: ConfirmDialogData,
    private dialogRef: MatDialogRef<ConfirmDialogComponent>,
  ) {}

  title(): string {
    return this.dialogData?.title ?? '';
  }

  message(): string {
    return this.dialogData?.message ?? '';
  }

  type(): ConfirmDialogType {
    return this.dialogData?.type ?? 'warning';
  }

  confirmText(): string {
    return this.dialogData?.confirmText ?? 'Confirmar';
  }

  cancelText(): string {
    return this.dialogData?.cancelText ?? 'Cancelar';
  }

  confirmColor(): 'primary' | 'error' | 'warning' | 'success' {
    return this.dialogData?.confirmColor ?? 'primary';
  }

  isLoading(): boolean {
    return this.dialogData?.isLoading ?? false;
  }

  iconBg(): string {
    switch (this.type()) {
      case 'error': return 'var(--color-errorSoft)';
      case 'info': return 'var(--color-infoSoft)';
      case 'success': return 'var(--color-successSoft)';
      default: return 'var(--color-warningSoft)';
    }
  }

  iconColor(): string {
    switch (this.type()) {
      case 'error': return 'var(--color-error)';
      case 'info': return 'var(--color-primary)';
      case 'success': return 'var(--color-success)';
      default: return 'var(--color-warning)';
    }
  }

  close(result: boolean): void {
    this.dialogRef.close(result);
  }

  confirm(): void {
    this.close(true);
  }
}

// src/common/components/modal/ConfirmDialog.tsx
import React from 'react';
import { Modal } from './Modal';
import { Button, Box, Typography } from '@mui/material';
import { AlertTriangle, CheckCircle, Info, XCircle } from 'lucide-react';

export type ConfirmDialogType = 'warning' | 'error' | 'info' | 'success';

interface ConfirmDialogProps {
    open: boolean;
    onClose: () => void;
    onConfirm: () => void;
    title: string;
    message: string;
    type?: ConfirmDialogType;
    confirmText?: string;
    cancelText?: string;
    confirmColor?: 'primary' | 'error' | 'warning' | 'success';
    isLoading?: boolean;
}

const typeConfig = {
    warning: {
        icon: AlertTriangle,
        color: 'var(--color-warning)',
        bgColor: 'var(--color-warningSoft)',
    },
    error: {
        icon: XCircle,
        color: 'var(--color-error)',
        bgColor: 'var(--color-errorSoft)',
    },
    info: {
        icon: Info,
        color: 'var(--color-primary)',
        bgColor: 'var(--color-infoSoft)',
    },
    success: {
        icon: CheckCircle,
        color: 'var(--color-success)',
        bgColor: 'var(--color-successSoft)',
    },
};

export const ConfirmDialog: React.FC<ConfirmDialogProps> = ({
    open,
    onClose,
    onConfirm,
    title,
    message,
    type = 'warning',
    confirmText = 'Confirmar',
    cancelText = 'Cancelar',
    confirmColor = 'primary',
    isLoading = false,
}) => {
    const config = typeConfig[type];
    const Icon = config.icon;

    const handleConfirm = () => {
        onConfirm();
    };

    return (
        <Modal
            open={open}
            onClose={onClose}
            title={title}
            maxWidth="sm"
            disableBackdropClick={isLoading}
            actions={
                <Box sx={{ display: 'flex', gap: 1.5, width: '100%' }}>
                    <Button
                        onClick={onClose}
                        disabled={isLoading}
                        variant="outlined"
                        sx={{
                            flex: 1,
                            borderRadius: '16px',
                            textTransform: 'none',
                            py: 1.2,
                            fontWeight: 600,
                            borderColor: 'var(--color-border)',
                            color: 'var(--color-text)',
                            '&:hover': {
                                borderColor: 'var(--color-primary)',
                                backgroundColor: 'var(--color-hover)',
                            },
                        }}
                    >
                        {cancelText}
                    </Button>
                    <Button
                        onClick={handleConfirm}
                        disabled={isLoading}
                        variant="contained"
                        color={confirmColor}
                        sx={{
                            flex: 1,
                            borderRadius: '16px',
                            textTransform: 'none',
                            py: 1.2,
                            fontWeight: 600,
                            transition: 'all 0.3s ease',
                            '&:hover': {
                                transform: 'translateY(-1px)',
                                boxShadow: '0 8px 20px var(--color-buttonShadow)',
                            },
                        }}
                    >
                        {isLoading ? 'Procesando...' : confirmText}
                    </Button>
                </Box>
            }
        >
            <Box
                sx={{
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'center',
                    gap: 2,
                    py: 2,
                }}
            >
                <Box
                    sx={{
                        width: 64,
                        height: 64,
                        borderRadius: '50%',
                        backgroundColor: config.bgColor,
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                    }}
                >
                    <Icon size={32} color={config.color} />
                </Box>

                <Typography
                    variant="body1"
                    sx={{
                        color: 'var(--color-text)',
                        textAlign: 'center',
                        opacity: 0.9,
                        lineHeight: 1.6,
                    }}
                >
                    {message}
                </Typography>
            </Box>
        </Modal>
    );
};

export default ConfirmDialog;
