// src/common/components/layout/UserProfile.tsx
import React, { useState } from 'react';
import { Box, Typography, Menu, MenuItem, Avatar, Divider } from '@mui/material';
import { LogOut, Settings, ChevronDown } from 'lucide-react';
import { useAuthStore } from '@/common/stores/auth-store';
import { useNavigate } from 'react-router';
import { useMutationQuery } from '@/hooks/api/useMutationQuery';

export const UserProfile: React.FC = () => {
    const { user, logoutUser } = useAuthStore();
    const navigate = useNavigate();
    const [anchorEl, setAnchorEl] = useState<null | HTMLElement>(null);
    const open = Boolean(anchorEl);

    const logout = useMutationQuery({ url: 'auth/logout', method: 'POST' });

    const handleClick = (event: React.MouseEvent<HTMLElement>) => {
        setAnchorEl(event.currentTarget);
    };

    const handleClose = () => {
        setAnchorEl(null);
    };

    const handleLogout = async () => {
        handleClose();
        try {
            await logout.mutateAsync(null);
        } catch {
            // Error ya manejado por el interceptor
        }
        logoutUser();
        navigate('/auth/login');
    };

    const handleSettings = () => {
        handleClose();
        navigate('/settings');
    };

    if (!user) return null;

    // Obtener iniciales del nombre
    const getInitials = (name: string) => {
        return name
            .split(' ')
            .map(n => n[0])
            .join('')
            .toUpperCase()
            .slice(0, 2);
    };

    return (
        <>
            <Box
                onClick={handleClick}
                sx={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: 1.5,
                    cursor: 'pointer',
                    p: 1,
                    borderRadius: '12px',
                    transition: 'all 0.2s ease',
                    '&:hover': {
                        backgroundColor: 'var(--color-hover)',
                    }
                }}
            >
                <Avatar
                    sx={{
                        width: 40,
                        height: 40,
                        backgroundColor: 'var(--color-primary)',
                        color: 'white',
                        fontWeight: 700,
                        fontSize: '0.9rem',
                        border: '2px solid var(--color-border)',
                    }}
                >
                    {getInitials(user.fullName)}
                </Avatar>
                <Box sx={{ display: { xs: 'none', md: 'flex' }, flexDirection: 'column', alignItems: 'flex-start' }}>
                    <Typography
                        variant="body2"
                        sx={{
                            fontWeight: 600,
                            color: 'var(--color-text)',
                            lineHeight: 1.2,
                        }}
                    >
                        {user.fullName}
                    </Typography>
                    <Typography
                        variant="caption"
                        sx={{
                            color: 'var(--color-text)',
                            opacity: 0.7,
                            fontSize: '0.75rem',
                        }}
                    >
                        {user.email}
                    </Typography>
                </Box>
                <ChevronDown
                    size={18}
                    style={{
                        color: 'var(--color-text)',
                        opacity: 0.7,
                        transition: 'transform 0.2s ease',
                        transform: open ? 'rotate(180deg)' : 'rotate(0deg)',
                    }}
                />
            </Box>

            <Menu
                anchorEl={anchorEl}
                open={open}
                onClose={handleClose}
                anchorOrigin={{
                    vertical: 'bottom',
                    horizontal: 'right',
                }}
                transformOrigin={{
                    vertical: 'top',
                    horizontal: 'right',
                }}
                PaperProps={{
                    sx: {
                        mt: 1,
                        minWidth: 220,
                        borderRadius: '16px',
                        border: '1px solid var(--color-border)',
                        backgroundColor: 'var(--color-background)',
                        backdropFilter: 'blur(20px)',
                        boxShadow: '0 10px 40px rgba(0, 0, 0, 0.15)',
                        overflow: 'hidden',
                    }
                }}
            >
                <Box sx={{ p: 2, pb: 1.5 }}>
                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5 }}>
                        <Avatar
                            sx={{
                                width: 48,
                                height: 48,
                                backgroundColor: 'var(--color-primary)',
                                color: 'white',
                                fontWeight: 700,
                                fontSize: '1.1rem',
                            }}
                        >
                            {getInitials(user.fullName)}
                        </Avatar>
                        <Box>
                            <Typography
                                variant="body2"
                                sx={{
                                    fontWeight: 600,
                                    color: 'var(--color-text)',
                                }}
                            >
                                {user.fullName}
                            </Typography>
                            <Typography
                                variant="caption"
                                sx={{
                                    color: 'var(--color-text)',
                                    opacity: 0.7,
                                    fontSize: '0.75rem',
                                }}
                            >
                                {user.email}
                            </Typography>
                        </Box>
                    </Box>
                </Box>

                <Divider sx={{ borderColor: 'var(--color-border)' }} />

                <MenuItem
                    onClick={handleSettings}
                    sx={{
                        py: 1.5,
                        px: 2,
                        gap: 1.5,
                        color: 'var(--color-text)',
                        '&:hover': {
                            backgroundColor: 'var(--color-hover)',
                        }
                    }}
                >
                    <Settings size={18} />
                    <Typography variant="body2">Configuración</Typography>
                </MenuItem>

                <Divider sx={{ borderColor: 'var(--color-border)' }} />

                <MenuItem
                    onClick={handleLogout}
                    sx={{
                        py: 1.5,
                        px: 2,
                        gap: 1.5,
                        color: 'var(--color-error)',
                        '&:hover': {
                            backgroundColor: 'rgba(239, 68, 68, 0.1)',
                        }
                    }}
                >
                    <LogOut size={18} />
                    <Typography variant="body2">Cerrar sesión</Typography>
                </MenuItem>
            </Menu>
        </>
    );
};

export default UserProfile;

// src/app/layout/user-profile.component.ts
import { Component, signal } from '@angular/core';
import { Router } from '@angular/router';
import { MatMenuModule } from '@angular/material/menu';
import { MatDividerModule } from '@angular/material/divider';
import { AuthStore } from '@core/auth/auth.store';
import { RequestService } from '@services/request.service';
import { UserAvatarComponent } from '@components/avatar/user-avatar.component';
import { LucideLogOut, LucideSettings, LucideUser, LucideChevronDown } from '@lucide/angular';

@Component({
  selector: 'app-user-profile',
  standalone: true,
  imports: [MatMenuModule, MatDividerModule, UserAvatarComponent, LucideLogOut, LucideSettings, LucideUser, LucideChevronDown],
  template: `
    @if (auth.user(); as user) {
      @if (user) {
        <div class="profile-trigger" [matMenuTriggerFor]="profileMenu" (menuOpened)="menuOpen.set(true)" (menuClosed)="menuOpen.set(false)">
          <span class="profile-avatar-border">
            <app-user-avatar [name]="user.fullName" [size]="40" fontSize="0.9rem"></app-user-avatar>
          </span>
          <div class="profile-info">
            <span class="profile-name">{{ user.fullName }}</span>
            <span class="profile-email">{{ user.email }}</span>
          </div>
          <svg class="chevron" [class.open]="menuOpen()" lucideChevronDown size="18"></svg>
        </div>

        <mat-menu #profileMenu="matMenu" class="profile-menu" [xPosition]="'before'" [yPosition]="'below'" [hasBackdrop]="true" [backdropClass]="''">
          <ng-template matMenuContent>
            <div class="menu-header">
              <app-user-avatar [name]="user.fullName" [size]="48" fontSize="1.1rem"></app-user-avatar>
              <div class="menu-text">
                <div class="menu-title">{{ user.fullName }}</div>
                <div class="menu-subtitle">{{ user.email }}</div>
              </div>
            </div>
            <mat-divider></mat-divider>
            <button mat-menu-item (click)="goProfile()">
              <svg lucideUser size="18"></svg>
              <span>Perfil</span>
            </button>
            <button mat-menu-item (click)="goSettings()">
              <svg lucideSettings size="18"></svg>
              <span>Configuración</span>
            </button>
            <mat-divider></mat-divider>
            <button mat-menu-item class="logout-item" (click)="handleLogout()">
              <svg lucideLogOut size="18"></svg>
              <span>Cerrar sesión</span>
            </button>
          </ng-template>
        </mat-menu>
      }
    }
  `,
  styles: [`
    .profile-trigger {
      display: flex;
      align-items: center;
      gap: 12px;
      cursor: pointer;
      padding: 8px;
      border-radius: 12px;
      transition: all 0.2s ease;
    }
    .profile-trigger:hover { background-color: var(--color-hover); }
    .profile-avatar-border { display: flex; flex-shrink: 0; }
    .profile-info { display: flex; flex-direction: column; align-items: flex-start; min-width: 0; }
    .profile-name { font-weight: 600; color: var(--color-text); line-height: 1.2; font-size: 0.875rem; white-space: nowrap; }
    .profile-email { color: var(--color-text); opacity: 0.7; font-size: 0.75rem; white-space: nowrap; }
    .chevron { color: var(--color-text); opacity: 0.7; transition: transform 0.2s ease; flex-shrink: 0; }
    .chevron.open { transform: rotate(180deg); }
    .menu-header {
      display: flex;
      align-items: center;
      gap: 12px;
      padding: 16px 16px 12px 16px;
    }
    .menu-text { display: flex; flex-direction: column; min-width: 0; }
    .menu-title { font-weight: 600; color: var(--color-text); font-size: 0.875rem; white-space: nowrap; }
    .menu-subtitle { color: var(--color-text); opacity: 0.7; font-size: 0.75rem; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
    .logout-item { color: var(--color-error) !important; }
  `],
})
export class UserProfileComponent {
  readonly menuOpen = signal(false);

  constructor(
    public auth: AuthStore,
    private router: Router,
    private request: RequestService,
  ) {}

  goProfile(): void {
    void this.router.navigate(['/profile']);
  }

  goSettings(): void {
    void this.router.navigate(['/settings']);
  }

  handleLogout(): void {
    const request = this.request.create({ url: 'auth/logout', method: 'POST' });
    void request.execute(null).finally(() => {
      this.auth.logoutUser();
      void this.router.navigate(['/auth/login']);
    });
  }
}
