// src/components/cards/InfoCard.tsx
import { Box, Typography } from "@mui/material";
import { MainCard } from "./MainCard";
import type { ElementType } from "react";

interface Props {
    label: string;
    value: string;
    icon: ElementType<{ size?: number }>;
    colorToken?: string;
}

export const InfoCard = ({ label, value, icon: Icon, colorToken }: Props) => (
    <MainCard sx={{ height: '100%' }}>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
            <Box
                sx={{
                    width: 40,
                    height: 40,
                    borderRadius: '12px',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    backgroundColor: colorToken ? `var(--color-${colorToken}Soft)` : 'var(--color-primarySoft)',
                    color: colorToken ? `var(--color-${colorToken})` : 'var(--color-primary)',
                    flexShrink: 0,
                }}
            >
                <Icon size={18} />
            </Box>
            <Box sx={{ minWidth: 0 }}>
                <Typography
                    variant="caption"
                    sx={{
                        color: 'var(--color-text)',
                        opacity: 0.6,
                        fontWeight: 500,
                        fontSize: '0.7rem',
                        display: 'block',
                        lineHeight: 1.4,
                    }}
                >
                    {label}
                </Typography>
                <Typography
                    variant="body2"
                    sx={{
                        color: 'var(--color-text)',
                        fontWeight: 500,
                        fontSize: '0.9rem',
                        overflow: 'hidden',
                        textOverflow: 'ellipsis',
                        whiteSpace: 'nowrap',
                    }}
                    title={value}
                >
                    {value}
                </Typography>
            </Box>
        </Box>
    </MainCard>
);

// src/app/shared/components/cards/info-card.component.ts
import { Component, input } from '@angular/core';
import { MainCardComponent } from '@components/cards/main-card.component';

@Component({
  selector: 'app-info-card',
  standalone: true,
  imports: [MainCardComponent],
  template: `
    <app-main-card>
      <div class="info-row">
        <div class="info-icon" [style.backgroundColor]="iconBg()" [style.color]="iconColor()">
          <ng-content select="[icon]"></ng-content>
        </div>
        <div class="info-text">
          <div class="info-label">{{ label() }}</div>
          <div class="info-value" [title]="value()">{{ value() }}</div>
        </div>
      </div>
    </app-main-card>
  `,
  styles: `
    .info-row { display: flex; align-items: center; gap: 16px; }
    .info-icon { width: 40px; height: 40px; border-radius: 12px; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
    .info-text { min-width: 0; }
    .info-label { color: var(--color-text); opacity: 0.6; font-weight: 500; font-size: 0.7rem; line-height: 1.4; }
    .info-value { color: var(--color-text); font-weight: 500; font-size: 0.9rem; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  `,
})
export class InfoCardComponent {
  label = input('');
  value = input('');
  colorToken = input<string | undefined>(undefined);

  iconBg(): string {
    const token = this.colorToken();
    return token ? `var(--color-${token}Soft)` : 'var(--color-primarySoft)';
  }

  iconColor(): string {
    const token = this.colorToken();
    return token ? `var(--color-${token})` : 'var(--color-primary)';
  }
}
