// src/app/shared/components/cards/stats-card.component.ts
import { Component, input } from '@angular/core';
import { MainCardComponent } from '@components/cards/main-card.component';

@Component({
  selector: 'app-stats-card',
  standalone: true,
  imports: [MainCardComponent],
  template: `
    <app-main-card>
      <div class="stats-row">
        <div class="stats-text">
          <div class="stats-title">{{ title() }}</div>
          <div class="stats-value">{{ value() }}</div>
          @if (subtitle()) {
            <div class="stats-subtitle">{{ subtitle() }}</div>
          }
        </div>
        @if (icon()) {
          <div class="stats-icon" [style.backgroundColor]="iconBg()" [style.color]="iconColor()">
            <ng-content select="[icon]"></ng-content>
          </div>
        }
      </div>
    </app-main-card>
  `,
  styles: `
    .stats-row { display: flex; align-items: flex-start; justify-content: space-between; gap: 8px; }
    .stats-title { color: var(--color-text); opacity: 0.7; font-weight: 500; font-size: 0.875rem; margin-bottom: 4px; }
    .stats-value { color: var(--color-text); font-weight: 800; font-size: 1.7rem; line-height: 1.1; }
    .stats-subtitle { color: var(--color-text); opacity: 0.5; font-size: 0.75rem; margin-top: 4px; display: block; }
    .stats-icon {
      width: 44px; height: 44px; border-radius: 12px;
      display: flex; align-items: center; justify-content: center; flex-shrink: 0;
    }
  `,
})
export class StatsCardComponent {
  title = input('');
  value = input<number | string>('');
  colorToken = input<string | undefined>(undefined);
  subtitle = input('');
  icon = input(true);

  iconBg(): string {
    const token = this.colorToken();
    return token ? `var(--color-${token}Soft)` : 'var(--color-primarySoft)';
  }

  iconColor(): string {
    const token = this.colorToken();
    return token ? `var(--color-${token})` : 'var(--color-primary)';
  }
}

// src/pages/private/dashboard/components/StatsCard.tsx
import { MainCard } from "@/common/components/Cards/MainCard";
import { Typography, Box } from "@mui/material";

interface StatsCardProps {
  title: string;
  value: number | string;
  icon: React.ReactNode;
  colorToken?: string;
  subtitle?: string;
}

export const StatsCard = ({ title, value, icon, colorToken, subtitle }: StatsCardProps) => (
  <MainCard sx={{ height: '100%' }}>
    <Box sx={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 1 }}>
      <Box>
        <Typography variant="body2" sx={{ color: 'var(--color-text)', opacity: 0.7, fontWeight: 500, mb: 0.5 }}>
          {title}
        </Typography>
        <Typography variant="h4" sx={{ fontWeight: 800, color: 'var(--color-text)', lineHeight: 1.1 }}>
          {value}
        </Typography>
        {subtitle && (
          <Typography variant="caption" sx={{ color: 'var(--color-text)', opacity: 0.5, mt: 0.5, display: 'block' }}>
            {subtitle}
          </Typography>
        )}
      </Box>
      <Box
        sx={{
          width: 44,
          height: 44,
          borderRadius: '12px',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          backgroundColor: colorToken ? `var(--color-${colorToken}Soft)` : 'var(--color-primarySoft)',
          color: colorToken ? `var(--color-${colorToken})` : 'var(--color-primary)',
          flexShrink: 0,
        }}
      >
        {icon}
      </Box>
    </Box>
  </MainCard>
);
