// src/common/components/tables/mainTable/NoData.tsx
import { Box } from "@mui/material";
import { Inbox, SearchX } from "lucide-react";
import type React from "react";

interface Props {
  name?: string,
  isFetched?: boolean,
  emptyLabel?: string,
  filterLabel?: string,
}

export const NoData: React.FC<Props> = ({ 
  isFetched,
  name,
  emptyLabel,
  filterLabel
}) => {
  const message = isFetched 
    ? (emptyLabel || 'NO HAY DATOS') 
    : (filterLabel || `Usa los filtros para listar ${name || 'datos'}`)

  return (
    <Box
      display="flex"
      flexDirection="column"
      alignItems="center"
      justifyContent="center"
      gap={1}
      height='100%'
      width='100%'
      sx={{ 
        userSelect: 'none',
        py: 6,
        opacity: 0.55,
      }}
      color='var(--color-text)'
    >
      {isFetched ? <Inbox size={60} strokeWidth={1.5} /> : <SearchX size={60} strokeWidth={1.5} />}
      <span style={{ fontSize: '1rem', fontWeight: 600 }}>{message}</span>
    </Box>
  );
};

// src/app/shared/components/tables/no-data.component.ts
import { Component, input } from '@angular/core';
import { LucideInbox, LucideSearchX } from '@lucide/angular';

@Component({
  selector: 'app-no-data',
  standalone: true,
  imports: [LucideInbox, LucideSearchX],
  template: `
    <div class="ale-nodata">
      @if (isFetched()) {
        <svg lucideInbox [style.width.px]="60" [style.height.px]="60"></svg>
      } @else {
        <svg lucideSearchX [style.width.px]="60" [style.height.px]="60"></svg>
      }
      <span>{{ message }}</span>
    </div>
  `,
  styles: [`
    .ale-nodata {
      display: flex; flex-direction: column; align-items: center; justify-content: center;
      gap: 8px; width: 100%; user-select: none; padding: 48px 0; opacity: 0.55; color: var(--color-text);
    }
    .ale-nodata span { font-size: 1rem; font-weight: 600; }
  `],
})
export class NoDataComponent {
  name = input<string>();
  isFetched = input<boolean>();
  emptyLabel = input<string>();
  filterLabel = input<string>();

  get message(): string {
    if (this.isFetched()) return this.emptyLabel() || 'NO HAY DATOS';
    return this.filterLabel() || `Usa los filtros para listar ${this.name() || 'datos'}`;
  }
}
